{"pagelen": 100, "values": [{"changes": {"content": {"new": "# Description\r\n\r\nIf an urdf file has meshes defined with relative path wrt the model file \\(support introduced in [sdformat#558](#!/osrf/sdformat/pull-requests/558/accept-relative-path-in)\\), the meshes are not found.\r\n\r\nThe setup is the following:\r\n\r\n* A world file with a ground plane and an `<include><uri>` of the model file \\(the model\u2019s parent folder is part of `SDF_PATH`\\). The world file is in an external folder far away from the model / mesh files.\r\n* A urdf model that uses relative path to the mesh files \\(mesh files are inside a `meshes` subfolder of the model\u2019s directory\\).\r\n* A `model.config` file in the same folder of the urdf model that loads the urdf with: `<sdf>icub.urdf</sdf>`.\r\n\r\nOpening the world with `ign gazebo /path/to/include_model.world` fails producing errors about meshes not found:\r\n\r\n```\r\n[Err] [SystemPaths.cc:428] Could not resolve file [urdf file/meshes/simmechanics/sim_sea_2-5_root_link_prt-binary.stl]\r\n[Err] [MeshManager.cc:172] Unable to find file[urdf file/meshes/simmechanics/sim_sea_2-5_root_link_prt-binary.stl]\r\n[...]\r\n[GUI] [Err] [SystemPaths.cc:428] Could not resolve file [urdf file/meshes/simmechanics/sim_sea_2-5_root_link_prt-binary.stl]\r\n[GUI] [Err] [MeshManager.cc:172] Unable to find file[urdf file/meshes/simmechanics/sim_sea_2-5_root_link_prt-binary.stl]\r\n[GUI] [Err] [MeshDescriptor.cc:56] Mesh manager can't find mesh named [urdf file/meshes/simmechanics/sim_sea_2-5_root_link_prt-binary.stl]\r\n[GUI] [Err] [OgreMeshFactory.cc:422] Cannot load null mesh\r\n[GUI] [Err] [SceneManager.cc:290] Failed to load geometry for visual: base_link_fixed_joint_lump__root_link_visual\r\n[...]\r\n```\r\n\r\nHowever, if I convert the urdf to sdf with `ign sdf -p model.urdf > model.sdf`, and modify the `model.config` to load the sdf, the meshes are found correctly.\r\n\r\n# Versions\r\n\r\nI\u2019m on ubuntu 18.04 with sdformat and ign-gazebo compiled from sources.\r\n\r\n* sdformat: `sdf9@`[8ba6c75](#!/osrf/sdformat/commits/8ba6c751ad4d9326fd8b3f14c8dc51d7c67a0ed3)\r\n* ign-gazebo: `ign-gazebo3@`[d42d5ba](https://bitbucket.org/ignitionrobotics/ign-gazebo/commits/d42d5badf2d41371d8567292e8e08b58f4f83d42)\r\n\r\n# Additional Information\r\n\r\nThe meshes folder is not on purpose inside `IGN_FILE_PATH`. If I add the folder to the env variable, meshes are found also in the urdf case \\(but the main point is that is should work also without this env var\\).\r\n\r\nIt seems to me that the relative path support for meshes works only if the model is already a sdf model. If, instead, the model is an urdf that needs to be converted, the link to the meshes cannot be resolved. I suspect that, since the conversion happens inside sdformat code, the folder where the original urdf code is located is somehow ignored and it is not included in the search path for meshes.\r\n\r\ncc @{557058:6ff86fcb-b7ab-44a5-b8a6-f6d9cae8b6e8}", "old": "# Description\r\n\r\nIf an urdf file has meshes defined with relative path wrt the model file \\(support introduced in [sdformat#558](#!/osrf/sdformat/pull-requests/558/accept-relative-path-in)\\), the meshes are not found.\r\n\r\nThe setup is the following:\r\n\r\n* A world file with a ground plane and an `<include><uri>` of the model file \\(the model\u2019s parent folder is part of `SDF_PATH`\\). The world file is in an external folder far away from the model / mesh files.\r\n* A urdf model that uses relative path to the mesh files \\(mesh files are inside a `meshes` subfolder of the model\u2019s directory\\).\r\n* A `model.config` file in the same folder of the urdf model that loads the urdf with: `<sdf>icub.urdf</sdf>`.\r\n\r\nOpening the world with `ign gazebo /path/to/include_model.world` fails producing errors about meshes not found.\r\n\r\nHowever, if I convert the urdf to sdf with `ign sdf -p model.urdf > model.sdf`, and modify the `model.config` to load the sdf, the meshes are found correctly.\r\n\r\n# Versions\r\n\r\nI\u2019m on ubuntu 18.04 with sdformat and ign-gazebo compiled from sources.\r\n\r\n* sdformat: `sdf9@`[8ba6c75](#!/osrf/sdformat/commits/8ba6c751ad4d9326fd8b3f14c8dc51d7c67a0ed3)\r\n* ign-gazebo: `ign-gazebo3@`[d42d5ba](https://bitbucket.org/ignitionrobotics/ign-gazebo/commits/d42d5badf2d41371d8567292e8e08b58f4f83d42)\r\n\r\n# Additional Information\r\n\r\nThe meshes folder is not on purpose inside `IGN_FILE_PATH`. If I add the folder to the env variable, meshes are found also in the urdf case \\(but the main point is that is should work also without this env var\\). \r\n\r\nIt seems to me that the relative path support for meshes works only if the model is already a sdf model. If, instead, the model is an urdf that needs to be converted, the link to the meshes cannot be resolved. I suspect that, since the conversion happens inside sdformat code, the folder where the original urdf code is located is somehow ignored and it is not included in the search path for meshes.\r\n\r\ncc @{557058:6ff86fcb-b7ab-44a5-b8a6-f6d9cae8b6e8}"}, "version": {"new": "1.5", "old": ""}}, "links": {"self": {"href": "data/repositories/osrf/sdformat/issues/227/changes/56152109.json"}, "html": {"href": "#!/osrf/sdformat/issues/227#comment-56152109"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/sdformat/issues/227.json"}}, "type": "issue", "id": 227, "repository": {"links": {"self": {"href": "data/repositories/osrf/sdformat.json"}, "html": {"href": "#!/osrf/sdformat"}, "avatar": {"href": "data/bytebucket.org/ravatar/{b6d52f9f-b070-41c0-807c-94af07ea375b}ts=1606789"}}, "type": "repository", "name": "sdformat", "full_name": "osrf/sdformat", "uuid": "{b6d52f9f-b070-41c0-807c-94af07ea375b}"}, "title": "Error loading meshes from a relative folder for urdf models"}, "created_on": "2020-02-12T21:49:31.176053+00:00", "user": {"display_name": "Diego Ferigo", "uuid": "{994b27a5-7d6d-42b2-8aa7-2ea82fbe7bf6}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B994b27a5-7d6d-42b2-8aa7-2ea82fbe7bf6%7D"}, "html": {"href": "https://bitbucket.org/%7B994b27a5-7d6d-42b2-8aa7-2ea82fbe7bf6%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:054df869-5cda-48f2-8b4e-81a61c133346/130cd3bf-aa0a-4355-bec2-c90f195acc4c/128"}}, "nickname": "dgferigo", "type": "user", "account_id": "557058:054df869-5cda-48f2-8b4e-81a61c133346"}, "message": {"raw": null, "markup": "markdown", "html": "", "type": "rendered"}, "type": "issue_change", "id": 56152109}], "page": 1, "size": 1}