{"links": {"self": {"href": "data/repositories/osrf/sdformat/pullrequests/602/comments/126247329.json"}, "html": {"href": "#!/osrf/sdformat/pull-requests/602/_/diff#comment-126247329"}}, "parent": {"id": 126245686, "links": {"self": {"href": "data/repositories/osrf/sdformat/pullrequests/602/comments/126245686.json"}, "html": {"href": "#!/osrf/sdformat/pull-requests/602/_/diff#comment-126245686"}}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 602, "links": {"self": {"href": "data/repositories/osrf/sdformat/pullrequests/602.json"}, "html": {"href": "#!/osrf/sdformat/pull-requests/602"}}, "title": "WIP: frame semantics -> libsdformat9"}, "content": {"raw": "It caught the error:\n\n```\n$ colcon build\n$ export IGN_CONFIG_PATH=${PWD}/install/sdformat9/share/ignition\n$ source ./install/setup.bash\n$ ign sdf --check ../../examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table_surface_only_collision.sdf\nError: relative_to name[world] specified by frame with name[top_center] does not match a link, joint, or frame name in model with name[extra_heavy_duty_table_surface_only_collision].\nError: invalid pose relative_to name.\nError: Invalid relative_to value in Frame.\nError in validatePoseRelativeToGraph: Non-MODEL vertex with name [top_center] should have 1 incoming edge in MODEL relative_to graph.\nError in resolvePoseRelativeToRoot for vertex named [top_center]: Source vertex found with name [top_center], but its name should be __model__.\nError: invalid pose relative_to graph.\n```\n\nHowever,  I would expect the same \\(or a related\\) error to be emitted by `SemanticPose::Resolve(\u2026)`\u2026\n\n\u200c", "markup": "markdown", "html": "<p>It caught the error:</p>\n<div class=\"codehilite\"><pre><span></span>$ colcon build\n$ <span class=\"nb\">export</span> <span class=\"nv\">IGN_CONFIG_PATH</span><span class=\"o\">=</span><span class=\"si\">${</span><span class=\"nv\">PWD</span><span class=\"si\">}</span>/install/sdformat9/share/ignition\n$ <span class=\"nb\">source</span> ./install/setup.bash\n$ ign sdf --check ../../examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table_surface_only_collision.sdf\nError: relative_to name<span class=\"o\">[</span>world<span class=\"o\">]</span> specified by frame with name<span class=\"o\">[</span>top_center<span class=\"o\">]</span> does not match a link, joint, or frame name in model with name<span class=\"o\">[</span>extra_heavy_duty_table_surface_only_collision<span class=\"o\">]</span>.\nError: invalid pose relative_to name.\nError: Invalid relative_to value in Frame.\nError in validatePoseRelativeToGraph: Non-MODEL vertex with name <span class=\"o\">[</span>top_center<span class=\"o\">]</span> should have <span class=\"m\">1</span> incoming edge in MODEL relative_to graph.\nError in resolvePoseRelativeToRoot <span class=\"k\">for</span> vertex named <span class=\"o\">[</span>top_center<span class=\"o\">]</span>: Source vertex found with name <span class=\"o\">[</span>top_center<span class=\"o\">]</span>, but its name should be __model__.\nError: invalid pose relative_to graph.\n</pre></div>\n\n\n<p>However,  I would expect the same (or a related) error to be emitted by <code>SemanticPose::Resolve(\u2026)</code>\u2026</p>\n<p>\u200c</p>", "type": "rendered"}, "created_on": "2019-11-25T21:13:12.890711+00:00", "user": {"display_name": "Eric Cousineau", "uuid": "{71c9fc05-02c8-45e1-adfa-13c8ac3399dc}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B71c9fc05-02c8-45e1-adfa-13c8ac3399dc%7D"}, "html": {"href": "https://bitbucket.org/%7B71c9fc05-02c8-45e1-adfa-13c8ac3399dc%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557057:f3a199b9-5784-4964-9644-6ef224bc7dc1/28a4d748-0fd4-4038-bf3d-55a77eb73ede/128"}}, "nickname": "eacousineau", "type": "user", "account_id": "557057:f3a199b9-5784-4964-9644-6ef224bc7dc1"}, "updated_on": "2019-11-25T21:13:13.108685+00:00", "type": "pullrequest_comment", "id": 126247329}